### ISSUE TITLE
Not able to execute the script without errors

### ISSUE THREAD

**Issue by louispaquin** [Kibbles/polyboot#1]
When I try to do a polyboot on a single phone I got theses errors message, do you have any idea how to fix this ?

What is the Python version you were running when you wrote the script ?

Thanks a lot!

C:\>polyboot.py -s 192.168.2.232 reboot 456
Traceback (most recent call last):
  File "C:\polyboot.py", line 128, in <module>
    reboot(ip)
  File "C:\polyboot.py", line 54, in reboot
    'Authorization: Basic ' + b64encode(admin_password),
  File "C:\Program Files\Python37\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

**Comment by Kibbles** [comment]
That particular error looks like it's originating from the `base64` library not liking the string it's being given. I originally wrote it for Python 3 and just tested it in Windows 10 with the 3.8 interpreter; it's working properly under those conditions, but the code is also a hot mess so it's very possible I'm missing something environment-specific.

**Comment by cbasolutions** [comment]
I created a pr to resolve based on my testing.
